services:
  app1:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./UserService
    container_name: app1
    depends_on:
      - db1
      - eureka-server
    ports:
      - "2432:2432"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:2431/userdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=u78s78er9
      - SERVER_PORT=2432
  db1:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_PASSWORD=u78s78er9
      - POSTGRES_USER=user
    ports:
      - "2431:2431"
    command: postgres -p 2431
  eureka-server:
    build:
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    restart: always