services:
  app2:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app2
    ports:
      - "2532:2532"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:2531/marketdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=u78s78er10
      - SERVER_PORT=2532